### ISSUE TITLE
app.php throws an error

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore-cli#18]
When running `php pimcore.phar pimcore5:migrate:filesystem` the command gets the latest skelleton from master: https://github.com/pimcore/pimcore-cli/blob/master/src/Cli/Command/Pimcore5/MigrateFilesystemCommand.php#L211

The Bootstrap function was renamed here:
https://github.com/pimcore/skeleton/commit/55e404f616ed53af6875528087803cb6f1980a2f#diff-64a0fd926147fcc158821dcb6f1b4d11

That function doesnt exist in Pimcore 5.4 and therefore throws an error.

**Comment by brusch** [comment]
Hmm, the question is how to fix that ... maybe by providing an option where you can specify the tag from which the data should be obtained?

**Comment by ultramegatom** [comment]
hmm would be an option. Or maybe simply make it a fixed version that works since this is not really changing anymore?

**Comment by skrahlQW** [comment]
@brusch Can you please provide the pimcore.phar for this build? Thanks!

**Comment by brusch** [comment]
@skrahlQW @ultramegatom here we go: https://github.com/pimcore/pimcore-cli/releases

**Comment by skrahlQW** [comment]
@brusch Thanks a lot. But are you sure the version you added to the MigrateFilesystemCommand.php file is correct? It seems v2.0.2 is Pimcore 6 according to composer.json. In my opinion, it has to be v1.0.2 for Pimcore 5.4...

**Comment by brusch** [comment]
v2.0.2 should work fine, since it's using the old method name.

**Comment by skrahlQW** [comment]
Ok. But we get the following error when trying to execute this migartion step: php bin/console pimcore:generate:bundle --namespace AppBundle

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Pimcore\Helper\LongRunningHelper": argument "$connectionRegistry" of method "__construct()" references interface "Doctrine\Common\Persistence\ConnectionRegistry" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in C:\projects\my-project\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass.php on line 37

Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Pimcore\Helper\LongRunningHelper": argument "$connectionRegistry" of method "__construct()" references interface "Doctrine\Common\Persistence\ConnectionRegistry" but no such service exists. It cannot be auto-registered because it is from a different root namespace. in C:\projects\my-project\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass.php on line 37

Call Stack:
    4.7265   54618856   1. Symfony\Component\Debug\ErrorHandler->handleException() C:\projects\my-project\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php:0`

I'm not sure if this is caused by the wrong version...

**Comment by brusch** [comment]
@skrahlQW thanks for your feedback, set it now back to the last v1 release (1.3.0), that one should be definitely compatible. Also tagged a new release (1.3.10), Phar should be available in a few minutes.
